repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Run ruff format
        entry: bash -c 'poetry run ruff format . --preview && git add .'
        language: system
        files: '\.py$'
